language: objective-c
osx_image: xcode8.3

env:
    global:
        - WORKSPACE=Jasmine.xcworkspace
        - SCHEME=Jasmine
        - SDK=iphonesimulator10.3
        - DESTINATION="platform=iOS Simulator,OS=latest,name=iPhone 7"

script:
    - xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -parallelizeTargets -enableCodeCoverage YES -quiet ONLY_ACTIVE_ARCH=YES
    - bash <(curl -s https://codecov.io/bash) -cF ios -J 'Jasmine'
